version: '3'
services:
  build_2.2:    
    build:
      context: ./
      dockerfile: Dockerfile.armhf
    image: mcfongtw/rpi-cassandra:2.2
  build_2.2.10:    
    build:
      context: ./
      dockerfile: Dockerfile.armhf
    image: mcfongtw/rpi-cassandra:2.2.11
  cassandra:
    image: mcfongtw/rpi-cassandra:2.2.11
    volumes:
      - /var/lib/cassandra:/var/lib/cassandra
    environment:
      ##################################################################
      # Cluster Name
      ################################################################## 
      - CASSANDRA_CLUSTER_NAME=Cassandra4PI

      ##################################################################
      # Extra parameters to enable JMX server for monitoring purposes
      - LOCAL_JMX=no
      # TODO: better to have hostname dynamically loaded.
      - JVM_EXTRA_OPTS=-Djava.rmi.server.hostname=192.168.2.168
      ##################################################################

      ################################################################## 
      # Expose the C* broadcast address for seed connection
      - CASSANDRA_BROADCAST_ADDRESS=192.168.2.168
      #- CASSANDRA_SEEDS=192.168.2.xx
      ##################################################################

      ################################################################## 
      # Number of tokens assigned to this node on the ring using vnodes. 
      - CASSANDRA_NUM_TOKENS=8
      ##################################################################

      ################################################################## 
      # Heap size
      #    Xmx=Xms=MAX_HEAP_SIZE
      #    Xmn=HEAP_NEWSIZE
      - MAX_HEAP_SIZE=384m
      - HEAP_NEWSIZE=96m
      ################################################################## 
    ports:
      # 7000: intra-node communication
      - "7000:7000"
      # 7001: TLS intra-node communication
      - "7001:7001"
      # 9042: CQL
      - "9042:9042"
      # 9160: thrift service
      - "9160:9160"
      # 7199: JMX
      - "7199:7199"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
