version: '3'
services:
  cassandra:
    build:
      context: ./
      dockerfile: Dockerfile.armhf
    image: rpi-cassandra:3.11
    volumes:
      - /var/lib/cassandra:/var/lib/cassandra
    ports:
      # 7000: intra-node communication
      - "7000:7000"
      # 7001: TLS intra-node communication
      - "7001:7001"
      # 9042: CQL
      - "9042:9042"
      # 9160: thrift service
      - "9160:9160"
      # 7199: JMX
      - "7199:7199"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
